apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: default
data:
  server.properties: |
    log.retention.hours=168
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
