name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Lint Kubernetes YAMLs
    - name: Lint Kubernetes manifests
      uses: yannh/kubeconform-action@v1
      with:
        files: 'k8s/**/*.yaml'

    # Build Docker images
    - name: Build Docker images
      run: |
        docker-compose build

    # Run unit tests (if applicable)
    - name: Run Python tests
      run: |
        pip install pytest
        pytest spark/jobs/

  deploy-to-k8s:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configure kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'

    # Authenticate with Kubernetes
    - name: Authenticate to Kubernetes cluster
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    # Deploy to Kubernetes
    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/
